#!/usr/bin/env bash

set -e
set -o pipefail

: "${ICLIBHOME:?ICLIBHOME undefined}"
export LD_LIBRARY_PATH=$ICLIBHOME:$LD_LIBRARY_PATH

# Emulate proc behavior w.r.t. source file
for arg
do
    case $arg in
    *=* ) case ${arg%%=*} in
        [iI][nN][aA][mM][eE] ) source=${arg#*=} ; break ;;
        esac ;;
    * ) source=$arg ; break ;;
    esac
done

{
    $ICSDKHOME/proc "$@" && rm ${source%.pc}.lis
} | sed 1,7d

# 'Error at line 3, column 10 in file mock-oracle.pc
# #include <stdarg.h>
# .........1
# PCC-S-02015, unable to open include file'

# Syntax error at line 17356, column 52, file
# /usr/include/AvailabilityInternal.h:
# Error at line 17356, column 52 in file /usr/include/AvailabilityInternal.h
# #define __API_AVAILABLE_GET_MACRO(_1,_2,_3,_4,NAME,...) NAME
# ...................................................1
# PCC-S-02014, Encountered the symbol "..." when expecting one of the following:
# 
#    an identifier, define, elif, else, endif, error, if, ifdef,
#    ifndef, include, line, pragma, undef, exec, sql, begin, end,
#    var, type, oracle, an immediate preprocessor command,
#    a C token, create, function, package, procedure, trigger, or,
#    replace,
#
